import assert from "node:assert/strict";
import { readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { PDF, SIZES, rgb } from "../dist/index.js";

const png = Uint8Array.from(Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lqL8WQAAAABJRU5ErkJggg==",
  "base64",
));

function text(bytes) {
  return Buffer.from(bytes).toString("latin1");
}

function assertPDF(bytes) {
  const source = text(bytes);
  assert.ok(source.startsWith("%PDF-1.4"));
  assert.ok(source.endsWith("%%EOF\n"));
  assert.match(source, /xref/);
}

test("exports page sizes and converts RGB colors", () => {
  assert.deepEqual(SIZES.A4, { width: 595, height: 842 });
  assert.deepEqual(SIZES.LETTER, { width: 612, height: 792 });
  assert.deepEqual(rgb(255, 0, 128), [1, 0, 128 / 255]);
});

test("creates drawing primitives, metadata, links, and pages", async (t) => {
  const pdf = await PDF.create();
  t.after(() => pdf.close());
  pdf
    .metadata({ title: "A (title)", author: "Ada", creator: "minpdf" })
    .text("Hello (JavaScript)", 50, 50, {
      size: 20,
      color: rgb(10, 20, 30),
      weight: "bold",
    })
    .rect(50, 80, 200, 50, {
      fill: rgb(52, 152, 219),
      stroke: rgb(0, 0, 0),
      lineWidth: 2,
      radius: 4,
    })
    .line(10, 150, 100, 150, { color: rgb(255, 0, 0), width: 2, dash: [3, 2] })
    .circle(150, 150, 20, { stroke: rgb(0, 0, 0) })
    .link("Website", "https://example.com?a=1&b=2", 20, 200)
    .page(SIZES.LETTER)
    .text("Second page", 20, 20);

  const bytes = pdf.bytes();
  assertPDF(bytes);
  const source = text(bytes);
  for (const expected of [
    "/Count 2",
    "/Helvetica-Bold",
    "/Title(A \\(title\\))",
    "/URI(https://example.com?a=1&b=2)",
    "[3.00 2.00 ] 0 d",
  ]) {
    assert.ok(source.includes(expected), `missing ${expected}`);
  }
});

test("renders tables with inferred widths and short rows", async (t) => {
  const pdf = await PDF.create();
  t.after(() => pdf.close());
  pdf.table(
    [["Ada", "Engineer"], ["Linus"]],
    20,
    20,
    { columns: [{ header: "Name" }, { header: "Role", align: "right" }] },
  );
  const source = text(pdf.bytes());
  for (const expected of ["(Name)", "(Role)", "(Ada)", "(Engineer)", "(Linus)"]) {
    assert.ok(source.includes(expected), `missing ${expected}`);
  }
});

test("embeds RGBA PNG images and returns a PDF blob", async (t) => {
  const pdf = await PDF.create();
  t.after(() => pdf.close());
  pdf.image(png, 10, 10, { width: 20 });
  const bytes = pdf.bytes();
  const source = text(bytes);
  assert.match(source, /\/Subtype\/Image/);
  assert.match(source, /\/SMask/);
  const blob = pdf.blob();
  assert.equal(blob.type, "application/pdf");
  assertPDF(new Uint8Array(await blob.arrayBuffer()));
});

test("save writes exactly the generated bytes", async (t) => {
  const pdf = await PDF.create();
  t.after(() => pdf.close());
  pdf.text("saved", 10, 10);
  const expected = pdf.bytes();
  const path = join(tmpdir(), `minpdf-${process.pid}-${Date.now()}.pdf`);
  t.after(() => rm(path, { force: true }));
  await pdf.save(path);
  assert.deepEqual(new Uint8Array(await readFile(path)), expected);
});

test("invalid engine arguments reject with useful errors", async (t) => {
  const pdf = await PDF.create();
  t.after(() => pdf.close());
  assert.throws(() => pdf.page({ width: 0, height: 100 }), /invalid page size/);
  assert.throws(() => pdf.rect(0, 0, -1, 1), /invalid rectangle/);
  assert.throws(() => pdf.circle(0, 0, -1), /invalid circle/);
  assert.throws(() => pdf.image(Uint8Array.from([1, 2, 3]), 0, 0), /invalid image/);
  assert.throws(() => pdf.text("x", 0, 0, { font: "missing" }), /font is not registered/);
  assert.throws(() => pdf.text("café", 0, 0), /non-ASCII text/);
});

test("close is idempotent", async () => {
  const pdf = await PDF.create();
  pdf.close();
  pdf.close();
});
